Repository gradle-dependency-analyze/gradle-dependency-analyze, pull requests merged in 2021-04, with the labels that each got.

#168 Allow defining aggregator dependencies in configuration
  README.md
  src/main/groovy/ca/cutterslade/gradle/analyze/AnalyzeDependenciesPlugin.groovy
  src/main/groovy/ca/cutterslade/gradle/analyze/AnalyzeDependenciesTask.groovy
  src/main/groovy/ca/cutterslade/gradle/analyze/ProjectDependencyResolver.groovy
  src/test/groovy/ca/cutterslade/gradle/analyze/AnalyzeDependenciesPluginAggregatorSpec.groovy
  src/test/groovy/ca/cutterslade/gradle/analyze/AnalyzeDependenciesPluginBaseSpec.groovy
  src/test/groovy/ca/cutterslade/gradle/analyze/AnalyzeDependenciesPluginGradleSpec.groovy
  src/test/groovy/ca/cutterslade/gradle/analyze/AnalyzeDependenciesPluginJavaTestFixturesSpec.groovy
  src/test/groovy/ca/cutterslade/gradle/analyze/AnalyzeDependenciesPluginSpec.groovy
Labels: enhancement, feature

#163 Update Gradle Wrapper from 6.8.3 to 7.0
  README.md
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
  src/test/groovy/ca/cutterslade/gradle/analyze/AnalyzeDependenciesPluginAggregatorSpec.groovy
  src/test/groovy/ca/cutterslade/gradle/analyze/AnalyzeDependenciesPluginGradleSpec.groovy
  src/test/groovy/ca/cutterslade/gradle/analyze/AnalyzeDependenciesPluginSpec.groovy
Labels: dependencies, gradle, gradle-wrapper

#91 Add log to file option
  README.md
  src/main/groovy/ca/cutterslade/gradle/analyze/AnalyzeDependenciesTask.groovy
  src/main/groovy/ca/cutterslade/gradle/analyze/ProjectDependencyResolver.groovy
Labels: enhancement, feature

#172 Adding a test to verify current state of constant detection capability
  README.md
  src/test/groovy/ca/cutterslade/gradle/analyze/AnalyzeDependenciesPluginBaseSpec.groovy
  src/test/groovy/ca/cutterslade/gradle/analyze/AnalyzeDependenciesPluginConstantsSpec.groovy
  src/test/groovy/ca/cutterslade/gradle/analyze/helper/GradleProject.groovy
  src/test/groovy/ca/cutterslade/gradle/analyze/helper/GroovyClass.groovy
Labels: documentation, wontfix
