Repository gradle-dependency-analyze/gradle-dependency-analyze, pull requests merged in 2022-03, with the labels that each got.

#273 Update Gradle Wrapper from 7.4 to 7.4.1
  gradle/wrapper/gradle-wrapper.properties
Labels: dependencies, gradle, gradle-wrapper, patch

#276 run build on pull request
  .github/workflows/build.yml
Labels: github-actions, fix

#275 Use the Gradle task configuration avoidance API (#274)
  src/main/groovy/ca/cutterslade/gradle/analyze/AnalyzeDependenciesPlugin.groovy
Labels: bug, enhancement, bugfix

#281 fix cannot access 'warnUsedUndeclared' variable
  src/main/groovy/ca/cutterslade/gradle/analyze/AnalyzeDependenciesTask.java
Labels: bugfix

#282 Update tests and readme to use task avoidance api
  README.md
  src/test/groovy/ca/cutterslade/gradle/analyze/helper/GradleProject.groovy
Labels: documentation
